// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/quickly":{"path":"guide/quickly","id":"docs/guide/quickly","parentId":"DocLayout"},"docs/guide/useForm":{"path":"guide/use-form","id":"docs/guide/useForm","parentId":"DocLayout"},"docs/guide/schema":{"path":"guide/schema","id":"docs/guide/schema","parentId":"DocLayout"},"docs/guide/widget":{"path":"guide/widget","id":"docs/guide/widget","parentId":"DocLayout"},"docs/guide/watch":{"path":"guide/watch","id":"docs/guide/watch","parentId":"DocLayout"},"docs/guide/rule":{"path":"guide/rule","id":"docs/guide/rule","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/guide/quickly': React.lazy(() => import(/* webpackChunkName: "docs__guide__quickly.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/quickly.md')),
'docs/guide/useForm': React.lazy(() => import(/* webpackChunkName: "docs__guide__useForm.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/useForm.md')),
'docs/guide/schema': React.lazy(() => import(/* webpackChunkName: "docs__guide__schema.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/schema.md')),
'docs/guide/widget': React.lazy(() => import(/* webpackChunkName: "docs__guide__widget.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/widget.md')),
'docs/guide/watch': React.lazy(() => import(/* webpackChunkName: "docs__guide__watch.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/watch.md')),
'docs/guide/rule': React.lazy(() => import(/* webpackChunkName: "docs__guide__rule.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/guide/rule.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/lvgx/Documents/workspace/packages/solo-form/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
