// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/lvgx/Documents/workspace/packages/solo-form/node_modules/.pnpm/dumi@2.2.1_breuhdo4c5bnlrgomjyu3xiyu4/node_modules/dumi/dist/client/theme-api/index.js';
